name: MLOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start MLflow Tracking Server
        run: |
          nohup mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 127.0.0.1 --port 5000 > mlflow.log 2>&1 &
          sleep 5
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000

      - name: Train model
        run: |
          python model.py train.csv

      - name: Evaluate model
        run: |
          python evaluate.py test.csv

      - name: Upload MLflow runs
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: ./mlruns

      - name: Upload evaluation results
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-results
          path: |
            result.csv
            fullResult.csv

      - name: Upload model metrics
        uses: actions/upload-artifact@v4
        with:
          name: model-metrics
          path: metrics_report.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          files: |
            metrics_report.txt
            result.csv
            fullResult.csv
            ./mlruns/**.pkl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
